name: build

on: push

env:
  CARGO_TERM_COLOR: always
  EMSCRIPTEN_VERSION: 3.1.39
  GODOT_VERSION: 4.2.2
  GODOT_PROJECT_PATH: godot

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            rust
      - name: Clippy
        run: |
          cd rust
          cargo clippy
      - name: rustfmt
        run: |
          cd rust
          cargo fmt --check

  build-rust:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - build_for: linux-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            bin: libblocks_plus_plus.so

          - build_for: wasm32
            os: ubuntu-22.04
            target: wasm32-unknown-emscripten
            bin: blocks_plus_plus.wasm

          - build_for: windows-x86_64
            os: windows-2022
            target: x86_64-pc-windows-msvc
            bin: blocks_plus_plus.dll

          - build_for: macos-x86_64
            os: macos-14
            target: x86_64-apple-darwin
            bin: libblocks_plus_plus.dylib

          - build_for: macos-aarch64
            os: macos-14
            target: aarch64-apple-darwin
            bin: libblocks_plus_plus.dylib

    name: Build Rust ${{ matrix.platform.build_for }}
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Emscripten
        if: contains(matrix.platform.target, 'wasm')
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EMSCRIPTEN_VERSION}}
          actions-cache-folder: 'emsdk-cache'
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            rust
      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          command: build
          args: "--locked --release ${{ contains(matrix.platform.target, 'wasm') && '-Zbuild-std' || ' '}}"
          strip: true
          working-directory: rust
          toolchain: ${{ contains(matrix.platform.target, 'wasm') && 'nightly' || 'stable' }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.build_for }}_${{ matrix.platform.bin }}
          path: rust/target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
  
  build-godot:
    # Based on https://github.com/abarichello/godot-ci
    strategy:
      fail-fast: false
      matrix:
        platform:
          - build_for: linux-x86_64
            export: linux_x11
            target: x86_64-unknown-linux-gnu
            bin: libblocks_plus_plus.so
            export_name: blocks-plus-plus.x86_64

          - build_for: wasm32
            export: web
            target: wasm32-unknown-emscripten
            bin: blocks_plus_plus.wasm
            export_name: index.html

          - build_for: windows-x86_64
            export: windows
            target: x86_64-pc-windows-msvc
            bin: blocks_plus_plus.dll
            export_name: blocks-plus-plus.exe

          - build_for: macos-x86_64
            export: macos
            target: x86_64-apple-darwin
            bin: libblocks_plus_plus.dylib
            export_name: blocks-plus-plus.zip

          # - build_for: macos-aarch64
          #   export: Mac OSX???
          #   target: aarch64-apple-darwin
          #   bin: libblocks_plus_plus.dylib
    
    needs: [lint-rust, build-rust]
    runs-on: ubuntu-22.04
    name: Build Godot ${{ matrix.platform.export }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Download rust bin
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.platform.build_for }}_${{ matrix.platform.bin }}
          path: rust/target/${{ matrix.platform.target }}/release/
      - name: Download rust linux bin  # We always need the bin for the platform we're running on, in the debug dir
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64_libblocks_plus_plus.so
          path: rust/target/x86_64-unknown-linux-gnu/debug/
      - name: Download custom templates
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: compile_godot.yaml
          workflow_search: true
          workflow_conclusion: success
          name: templates-${{env.GODOT_VERSION}}
          path: ~/.local/share/godot/export_templates/${{env.GODOT_VERSION}}.stable
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.platform.build_for }}
          cd $GODOT_PROJECT_PATH
          godot --headless --verbose --export-release ${{ matrix.platform.export }} ../build/${{ matrix.platform.build_for }}/${{ matrix.platform.export_name }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.build_for }}
          path: build/${{ matrix.platform.build_for }}
  
  publish-web:
    runs-on: ubuntu-22.04
    environment: main
    name: Publish Web
    needs: [build-godot]
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Web build
        uses: actions/download-artifact@v4
        with:
          name: wasm32
          path: wasm32
      - name: Add Cloudflare Pages files
        run: |
          cp deploy/cloudflare-pages/* wasm32/
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: blocks-plus-plus
          directory: wasm32
          wranglerVersion: '3'
          branch: ${{ github.head_ref || github.ref_name }}
